# ungrouped:
#   hosts:
#     localhost:
#       ansible_host: 0.0.0.0
app_group:
  hosts:
    managedhost-app-1:
      ansible_port: 2223
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
    managedhost-app-2:
      ansible_port: 2224
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
    managedhost-app-3:
      ansible_port: 2225
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root

# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# https://stackoverflow.com/questions/41094864/is-it-possible-to-write-ansible-hosts-inventory-files-in-yaml